version: '3.8'
services:
  vite-app:
    build:
        context: .
        dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - .:/app/react-app
      - /app/react-app/node_modules
